spring:
  application:
    name: attendance-face-recognize
  datasource:
    url: jdbc:mysql://localhost:3306/face_recognize
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  jpa:
    hibernate:
      ddl-auto: update   # create | update | validate | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  address: 0.0.0.0
  port: 8080


logging:
  level:
    org.springframework.security: DEBUG

